### ISSUE TITLE
[Bug] Predictive Model output has zeros in predictions 

### ISSUE THREAD

**Issue by melissa-garcia** [frahik/IBCF.MTME#2]
Hi, I was running the example from the paper for the cross-validation using the Wheat_IBCF data and my predicted values in the pm1$Data.Obs_pred comeback empty. See below:
![image](https://user-images.githubusercontent.com/45252844/48884806-f099dd80-ee75-11e8-81bd-d122667359c9.png)
Not sure what I'm doing wrong.

Thank you,

Melissa

**Comment by frahik** [comment]
Hi, Melissa,
You're doing it right, only you found a bug in the package. I'm already checking and patching to release a new version.
Thank you very much for reporting the issue.

On the other hand, you can solve it using the following codes:
pm$predictions_Summary
recovers the predicted and observed values for each of the test data used in each of the partitions.
Or you can use
summary(pm, information = 'complete')
summary(pm, information = 'compact')
to observe the predictive capacity of the model by trait and environment or by trait, environment and partition.

These implementations were added in the version of the package you are using.

**Comment by frahik** [comment]
This issue has been fixed in the development version of the package, to install it, use the following command:

```r
install.packages('devtools')
devtools::install_github('frahik/IBCF.MTME')
```

Or you can wait for the CRAN version to be released, I hope it will be released in approximately two days.
